#!/bin/bash
# Stage the GEM (Green Engineering Menu) CarPlay-RGI screen into the menu_install
# mod: mods/menu_install_MoreIncredibleBash/mod/carplay_menu/ (generated, gitignored).
#
#   ./scripts/build_gem_menu.sh
#
# One table below is the single source for the buttons. It generates
#   mib2q-carplay.esd                 the GEM screen (one "script" entry per button)
#   scripts/carplay/<button>.sh       one-line wrapper per button -> run.sh <action>
#   scripts/carplay/run.sh            dispatcher (deploy/gem_menu/run.sh)
#   scripts/carplay/actions/<mod>/    verbatim copies of mods/<mod>_MoreIncredibleBash/mod/custom.sh
# so a button always runs exactly what the matching M.I.B. mod runs.
set -e

[ "$#" -eq 0 ] || { echo "usage: ./scripts/build_gem_menu.sh"; exit 2; }

PROJECT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
MODS="$PROJECT_DIR/mods"
OUT="$MODS/menu_install_MoreIncredibleBash/mod/carplay_menu"
ON_UNIT=/mnt/app/eso/hmi/engdefs/scripts/carplay

# button script | run.sh action | GEM label
BUTTONS="
install|install|Install / update CarPlay (release on SD)
logs|logs|Save logs to SD (+ verbose on)
altscreen_on|altscreen_on|Cluster video (AltScreen) ON
altscreen_off|altscreen_off|Cluster video (AltScreen) OFF
rgd_enable|rgd_enable|Route guidance ON
rgd_disable|rgd_disable|Route guidance OFF
grid|grid|Calibration grid ON / OFF (toggle)
safearea|safearea|Apply SafeArea from SD (carplay_safearea*.conf)
safearea_reset|safearea_reset|Reset SafeArea to built-in
singleview|singleview|Classic-view SafeArea ON / OFF (2 ViewAreas)
reacquire|reacquire|Re-request cluster map (test app switching)
hwdec|hwdec|HW decoder ON / OFF (toggle, default ON)
aa_cluster_on|aa_cluster_on|Android Auto cluster map ON
aa_cluster_off|aa_cluster_off|Android Auto cluster map OFF
touchpad_dpad_on|touchpad_dpad_on|Touchpad as D-pad ON (CarPlay, default)
touchpad_dpad_off|touchpad_dpad_off|Touchpad as D-pad OFF (stock touchpad)
omxprobe|omxprobe|HW decoder probe (OMX, logs only)
lsd|lsd|Copy stock lsd.jxe to SD
uninstall|uninstall|Uninstall CarPlay (restore stock)
remove_menu|remove_menu|Remove this menu
"
# mod folders bundled as actions/<name>/custom.sh
ACTIONS="install uninstall logging extract_lsd altscreen_on altscreen_off rgd_enable rgd_disable altscreen_grid altscreen_safearea aa_cluster_on aa_cluster_off touchpad_dpad_on touchpad_dpad_off"

echo "=== GEM menu: staging $OUT ==="
rm -rf "$OUT"
mkdir -p "$OUT/scripts/carplay/actions"

for a in $ACTIONS; do
    src="$MODS/${a}_MoreIncredibleBash/mod/custom.sh"
    [ -s "$src" ] || { echo "ERROR: missing $src"; exit 1; }
    mkdir -p "$OUT/scripts/carplay/actions/$a"
    cp "$src" "$OUT/scripts/carplay/actions/$a/custom.sh"
done
cp "$PROJECT_DIR/deploy/gem_menu/run.sh" "$OUT/scripts/carplay/run.sh"

ESD="$OUT/mib2q-carplay.esd"
{
    echo "###########################################################################################"
    echo "# CarPlay-RGI (mib2q-carplay) - generated by scripts/build_gem_menu.sh, do not edit"
    echo "###########################################################################################"
    echo "screen \"CarPlay-RGI\" main"
    echo
    echo "keyValue"
    echo "    value   String sys 0x00000000 0"
    echo "    label   \"Same scripts as the M.I.B. mods. Install needs the release on SD in /mod/carplay/.\""
    echo "    poll    0"
} > "$ESD"

echo "$BUTTONS" | while IFS='|' read -r name action label; do
    [ -n "$name" ] || continue
    printf '#!/bin/sh\n# GEM CarPlay-RGI -> "%s"\nexec /bin/sh %s/run.sh %s\n' \
        "$label" "$ON_UNIT" "$action" > "$OUT/scripts/carplay/$name.sh"
    {
        echo
        echo "script"
        echo "   value   sys 1 0x0100 \"$ON_UNIT/$name.sh\""
        echo "   label   \"$label\""
    } >> "$ESD"
done

chmod 755 "$OUT"/scripts/carplay/*.sh "$OUT"/scripts/carplay/actions/*/custom.sh
echo "Staged $(grep -c '^script' "$ESD") GEM buttons, $(echo $ACTIONS | wc -w | tr -d ' ') actions."
